version: '2'
services:
  postgres:
    image: circleci/postgres
    container_name: postgres
    ports:
      - "5432:5432"

  application:
    build: ./
    links:
      - "postgres"
    container_name: rocker_crypt
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    command: bash -c "mix test && mix ecto.setup && mix phx.server"
